name: React basic demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: npm install

      - name: run tests
        run: npm test

      - name: linting
        run: npm run lint

      - name: building
        run: npm build
